# Site settings
title: VCE Algorithmics
email: vcealgo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An attempt to create a repository of VCE Algorithmics knowledge like Mark Kelly's vceit.com site.
  May or may not die, depending on how motivated I can be to continue it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vcealgorithmics.github.io" # the base hostname & protocol for your site
#twitter_username: vcealgorithmics
github_username:  vcealgorithmics

# Build settings
markdown: kramdown

# Other options
#permalink: blog/:year/:month/:title
#job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

gems:
  - jekyll-seo-tag
  - jekyll-sitemap